# BRONZE LAYER

## Buat Database

In [1]:
from sqlalchemy import create_engine, text


# Koneksi ke PostgreSQL server
DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"

# Nama database yang ingin dibuat
DB_NAME = "milestone1_omnichannel"


# Connect ke database bawaan PostgreSQL
engine = create_engine(DATABASE_URL, isolation_level="AUTOCOMMIT")


with engine.connect() as connection:

    # Cek apakah database sudah ada
    result = connection.execute(
        text("""
            SELECT 1
            FROM pg_database
            WHERE datname = :db_name
        """),
        {"db_name": DB_NAME}
    )

    database_exists = result.fetchone()

    if database_exists:
        print(f"Database '{DB_NAME}' sudah ada.")

    else:
        connection.execute(
            text(f'CREATE DATABASE "{DB_NAME}"')
        )

        print(f"Database '{DB_NAME}' berhasil dibuat.")

Database 'milestone1_omnichannel' sudah ada.

## 1. import dan connection

In [2]:
import json
import csv
import uuid
import hashlib
import pandas as pd

from datetime import datetime, timezone
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.engine import URL
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from pathlib import Path
#repo_root = Path.cwd()

#if not (repo_root / ".env").exists():
    #repo_root = repo_root.parent

#load_dotenv(repo_root / ".env")

#def required_env(name):
    #value = os.getenv(name)

    #if not value:
       # raise RuntimeError(
           # f"Missing required environment variable: {name}"
        #)

    #return value

engine = create_engine(
    URL.create(
        drivername="postgresql+psycopg2",
        username="postgres",
        password="postgres",
        host="localhost",
        port=5432,
        database="milestone1_omnichannel",
    )
)

print("Database connection berhasil.")

Database connection berhasil.

## 2. load file json dan csv

In [3]:
def load_json(path):
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list):
        return data

    if isinstance(data, dict):
        return [data]

    raise ValueError(f"Format JSON tidak didukung: {path}")


def load_csv(path):
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))

## 3. Checksum

In [4]:
def create_checksum(record):
    payload = json.dumps(
        record,
        sort_keys=True,
        ensure_ascii=False
    )
    return hashlib.sha256(
        payload.encode("utf-8")
    ).hexdigest()

## 4. Record

In [5]:
def get_source_record_id(record):
    if not isinstance(record, dict):
        return None

    preferred_keys = (
        "source_row_id",
        "event_id",
        "order_id",
        "order_item_id",
        "customer_id",
        "product_id",
        "promotion_id",
        "store_id",
        "channel_id",
        "category_id",
        "campaign_id",
        "address_id",
        "profile_id",
        "payment_id",
        "refund_id",
        "return_id",
        "support_id",
        "session_id",
    )

    for key in preferred_keys:
        value = record.get(key)

        if value is not None and value != "":
            return str(value)

    return None

## 5. cek file

In [7]:
import os
raw_dir = Path("../data/raw").resolve()
pipeline_run_id = os.getenv(
    "PIPELINE_RUN_ID",
    str(uuid.uuid4())
)
ingested_at = datetime.now(timezone.utc)
raw_files = sorted(
    path
    for path in raw_dir.rglob("*")
    if path.is_file()
    and path.name != "manifest.json"
    and path.suffix.lower() in {".json", ".csv"}
)

print("Jumlah file:", len(raw_files))

EXPECTED_FILES = [
    "operational/customers.json",
    "operational/customer_profiles.json",
    "operational/customer_addresses.json",
    "operational/products.json",
    "operational/product_categories.json",
    "operational/stores.json",
    "operational/sales_channels.json",
    "operational/promotions.json",
    "operational/orders.json",
    "operational/order_items.json",
    "operational/order_promotions.json",

    "events/payment_events.json",
    "events/refund_events.json",
    "events/return_events.json",
    "events/support_events.json",
    "events/web_events.json",

    "inventory/inventory_snapshots.csv",

    "reference/campaign_spend.csv",
    "reference/city_reference.json",
]


# Ambil semua file secara recursive
actual_files = [
    path
    for path in raw_dir.rglob("*")
    if path.is_file()
]


def normalize_path(path):
    return path.as_posix().lower()


missing_files = []
matched_files = {}


for expected in EXPECTED_FILES:

    expected_normalized = expected.lower()

    matches = [
        path
        for path in actual_files
        if normalize_path(path).endswith(expected_normalized)
    ]

    if not matches:
        missing_files.append(expected)

    else:
        matched_files[expected] = matches[0]


if missing_files:
    raise FileNotFoundError(
        "Raw files berikut tidak ditemukan:\n"
        + "\n".join(missing_files)
    )


print(
    f"Validasi berhasil: "
    f"{len(matched_files)}/{len(EXPECTED_FILES)} "
    "raw files ditemukan."
)

for expected, actual in matched_files.items():
    print(f"[OK] {expected}")

bronze_rows = []
for path in raw_files:
    source_file = path.relative_to(raw_dir).as_posix()
    if path.suffix.lower() == ".json":
        records = load_json(path)

    elif path.suffix.lower() == ".csv":
        records = load_csv(path)

    for row_number, record in enumerate(records, start=1):
        bronze_rows.append({
            "raw_record_id": str(uuid.uuid4()),
            "pipeline_run_id": pipeline_run_id,
            "ingested_at_utc": ingested_at,
            "source_file": source_file,
            "source_row_number": row_number,
            "source_record_id": get_source_record_id(record),
            "record_checksum": create_checksum(record),
            "raw_payload": record,
        })

print("Total Bronze records:", len(bronze_rows))

Jumlah file: 19
Validasi berhasil: 19/19 raw files ditemukan.
[OK] operational/customers.json
[OK] operational/customer_profiles.json
[OK] operational/customer_addresses.json
[OK] operational/products.json
[OK] operational/product_categories.json
[OK] operational/stores.json
[OK] operational/sales_channels.json
[OK] operational/promotions.json
[OK] operational/orders.json
[OK] operational/order_items.json
[OK] operational/order_promotions.json
[OK] events/payment_events.json
[OK] events/refund_events.json
[OK] events/return_events.json
[OK] events/support_events.json
[OK] events/web_events.json
[OK] inventory/inventory_snapshots.csv
[OK] reference/campaign_spend.csv
[OK] reference/city_reference.json
Total Bronze records: 158770

In [8]:
bronze_df = pd.DataFrame(bronze_rows) 
print(bronze_df.shape) 
bronze_df.head()

(158770, 8)

,raw_record_id,pipeline_run_id,ingested_at_utc,source_file,source_row_number,source_record_id,record_checksum,raw_payload
0,26cf01cb-f86a-4529-aa92-f512b29bce60,3fe81c91-4728-4347-8aba-daf36240d5d0,2026-09-23 18:19:14.802203+00:00,drive-download-20260922T154615Z-1-001/events/p...,1,EVT-00006883,6efa7a03aac06473e05c6655f8b650d9cca047e24545c8...,"{'event_id': 'EVT-00006883', 'event_type': 'PA..."
1,3f515df0-bba1-403e-9ec2-843ea5743625,3fe81c91-4728-4347-8aba-daf36240d5d0,2026-09-23 18:19:14.802203+00:00,drive-download-20260922T154615Z-1-001/events/p...,2,EVT-00010230,c653d58383dfadd565ea946a2080001f0175189d78a610...,"{'event_id': 'EVT-00010230', 'event_type': 'PA..."
2,affed191-5c96-4a48-9ec6-1b51d69ce5b9,3fe81c91-4728-4347-8aba-daf36240d5d0,2026-09-23 18:19:14.802203+00:00,drive-download-20260922T154615Z-1-001/events/p...,3,EVT-00051452,322e6fd0f77e248c8f01d1a34608907ea37ec62cbf0447...,"{'event_id': 'EVT-00051452', 'event_type': 'PA..."
3,5ee898c9-7f94-49b0-832e-28c03afc12f0,3fe81c91-4728-4347-8aba-daf36240d5d0,2026-09-23 18:19:14.802203+00:00,drive-download-20260922T154615Z-1-001/events/p...,4,EVT-00041158,52f35c19445a0de8fde9445c70916bb63181db60237228...,"{'event_id': 'EVT-00041158', 'event_type': 'PA..."
4,72a411db-3d27-437f-9002-cf3298a50cf9,3fe81c91-4728-4347-8aba-daf36240d5d0,2026-09-23 18:19:14.802203+00:00,drive-download-20260922T154615Z-1-001/events/p...,5,EVT-00055547,23ad2e952955075d435b47435a7d0b8fa0285c97b393fe...,"{'event_id': 'EVT-00055547', 'event_type': 'PA..."

In [ ]:
with engine.begin() as connection:

    connection.execute(text("""
        CREATE SCHEMA IF NOT EXISTS bronze;
    """))

    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS bronze.raw_records (
            raw_record_id UUID PRIMARY KEY,
            pipeline_run_id UUID NOT NULL,
            ingested_at_utc TIMESTAMPTZ NOT NULL,
            source_file TEXT NOT NULL,
            source_row_number INTEGER NOT NULL,
            source_record_id TEXT,
            record_checksum TEXT NOT NULL,
            raw_payload JSONB NOT NULL
        );
    """))

print("Schema dan tabel Bronze siap.")

Schema dan tabel Bronze siap.

## 6. Agar data tidak duplikat

In [ ]:
from sqlalchemy import text

with engine.connect() as connection:
    existing_checksums = pd.read_sql(
        text("""
            SELECT record_checksum
            FROM bronze.raw_records
        """),
        connection
    )

bronze_new = bronze_df[
    ~bronze_df["record_checksum"].isin(
        existing_checksums["record_checksum"]
    )
]

print("Total data       :", len(bronze_df))
print("Sudah ada        :", len(bronze_df) - len(bronze_new))
print("Data baru        :", len(bronze_new))

Total data       : 158770
Sudah ada        : 158770
Data baru        : 0

## 7. Masukin datanya

In [ ]:
bronze_new.to_sql(
    name="raw_records",
    con=engine,
    schema="bronze",
    if_exists="append",
    index=False,
    dtype={
        "raw_payload": JSONB
    }
)

print(f"Inserted {len(bronze_new)} Bronze records.")

Inserted 0 Bronze records.

In [ ]:
stored_bronze = pd.read_sql(
    text("""
        SELECT
            raw_record_id,
            pipeline_run_id,
            ingested_at_utc,
            source_file,
            source_row_number,
            source_record_id,
            record_checksum,
            raw_payload
        FROM bronze.raw_records
        WHERE pipeline_run_id = :pipeline_run_id
    """),
    engine,
    params={
        "pipeline_run_id": pipeline_run_id
    },
)

In [ ]:
stored_bronze.groupby(
    "source_file"
).size().sort_index()

source_file
drive-download-20260922T154615Z-1-001/events/payment_events.json             11275
drive-download-20260922T154615Z-1-001/events/refund_events.json               2079
drive-download-20260922T154615Z-1-001/events/return_events.json               1791
drive-download-20260922T154615Z-1-001/events/support_events.json              1478
drive-download-20260922T154615Z-1-001/events/web_events.json                 15579
drive-download-20260922T154615Z-1-001/inventory/inventory_snapshots.csv      17476
drive-download-20260922T154615Z-1-001/operational/customer_addresses.json     1265
drive-download-20260922T154615Z-1-001/operational/customer_profiles.json      1432
drive-download-20260922T154615Z-1-001/operational/customers.json              1209
drive-download-20260922T154615Z-1-001/operational/order_items.json           12413
drive-download-20260922T154615Z-1-001/operational/order_promotions.json       7813
drive-download-20260922T154615Z-1-001/operational/orders.json                 4966
drive-download-20260922T154615Z-1-001/operational/product_categories.json       42
drive-download-20260922T154615Z-1-001/operational/products.json                 45
drive-download-20260922T154615Z-1-001/operational/promotions.json                5
drive-download-20260922T154615Z-1-001/operational/sales_channels.json            1
drive-download-20260922T154615Z-1-001/operational/stores.json                    2
drive-download-20260922T154615Z-1-001/reference/campaign_spend.csv             417
drive-download-20260922T154615Z-1-001/reference/city_reference.json              5
dtype: int64

In [ ]:
stored_bronze[

    [

        "source_file",

        "source_record_id",

        "raw_payload"

    ]

].head()



first_payload = stored_bronze.loc[0, "raw_payload"]



print(type(first_payload))

print(first_payload)

<class 'dict'>
{'payload': {'amount': 2172.62, 'order_id': 'ORD-001121', 'payment_id': 'PAY-ORD-001121'}, 'event_id': 'EVT-00006883', 'event_type': 'PAYMENT_CAPTURED', 'ingested_at_utc': '2026-07-20T01:14:00Z', 'occurred_at_utc': '2026-07-19T18:14:00Z'}

## Bagian Akhir hanya untuk cek

In [ ]:
# ============================================================
# LOAD BRONZE DARI POSTGRESQL UNTUK QUALITY CHECK
# ============================================================

from sqlalchemy import create_engine, text
import pandas as pd

DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/milestone1_omnichannel"

engine = create_engine(DATABASE_URL)

# Tes koneksi
with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database();"))
    print("Connected to:", result.scalar())
    
import pandas as pd
from sqlalchemy import text

bronze = pd.read_sql(
    text("""
        SELECT *
        FROM bronze.raw_records
    """),
    engine
)

print("Bronze berhasil dimuat:", len(bronze), "rows")

# FINAL QUALITY CHECK - BRONZE LAYER
# ============================================================

quality_results = []

def add_check(check_name, actual, expected, passed):
    quality_results.append({
        "check_name": check_name,
        "actual": actual,
        "expected": expected,
        "status": "PASS" if passed else "FAIL"
    })


# 1. Bronze tidak boleh kosong
bronze_count = len(bronze)

add_check(
    "Bronze contains records",
    bronze_count,
    "> 0",
    bronze_count > 0
)


# 2. raw_payload wajib tersedia
null_payload = bronze["raw_payload"].isna().sum()

add_check(
    "Null raw_payload",
    null_payload,
    0,
    null_payload == 0
)


# 3. source_file wajib tersedia
null_source_file = bronze["source_file"].isna().sum()

add_check(
    "Null source_file",
    null_source_file,
    0,
    null_source_file == 0
)


# 4. source_row_number wajib tersedia
null_source_row = bronze["source_row_number"].isna().sum()

add_check(
    "Null source_row_number",
    null_source_row,
    0,
    null_source_row == 0
)


# 5. checksum wajib tersedia
null_checksum = bronze["record_checksum"].isna().sum()

add_check(
    "Null record_checksum",
    null_checksum,
    0,
    null_checksum == 0
)


# 6. pipeline_run_id wajib tersedia
null_pipeline_run = bronze["pipeline_run_id"].isna().sum()

add_check(
    "Null pipeline_run_id",
    null_pipeline_run,
    0,
    null_pipeline_run == 0
)


# 7. raw_record_id wajib unik
duplicate_raw_id = bronze["raw_record_id"].duplicated().sum()

add_check(
    "Duplicate raw_record_id",
    duplicate_raw_id,
    0,
    duplicate_raw_id == 0
)


# ============================================================
# TAMPILKAN REPORT
# ============================================================

bronze_quality_report = pd.DataFrame(quality_results)

display(bronze_quality_report)


# ============================================================
# FINAL BRONZE QUALITY GATE
# ============================================================

failed_checks = bronze_quality_report[
    bronze_quality_report["status"] == "FAIL"
]

print("=" * 60)
print("FINAL BRONZE QUALITY GATE")
print("=" * 60)

print("Total Bronze rows :", bronze_count)
print("Null raw_payload  :", null_payload)
print("Null source_file  :", null_source_file)
print("Null source row   :", null_source_row)
print("Null checksum     :", null_checksum)
print("Null pipeline run :", null_pipeline_run)
print("Duplicate raw ID  :", duplicate_raw_id)

print("=" * 60)

if len(failed_checks) == 0:
    print("✅ BRONZE QUALITY GATE: PASS")
    print("Bronze layer siap digunakan oleh Silver.")
else:
    print("❌ BRONZE QUALITY GATE: FAIL")
    print("Jumlah check gagal:", len(failed_checks))
    display(failed_checks)

Connected to: milestone1_omnichannel
Bronze berhasil dimuat: 158770 rows

                check_name  actual expected status
0  Bronze contains records  158770      > 0   PASS
1         Null raw_payload       0        0   PASS
2         Null source_file       0        0   PASS
3   Null source_row_number       0        0   PASS
4     Null record_checksum       0        0   PASS
5     Null pipeline_run_id       0        0   PASS
6  Duplicate raw_record_id       0        0   PASS

============================================================
FINAL BRONZE QUALITY GATE
============================================================
Total Bronze rows : 158770
Null raw_payload  : 0
Null source_file  : 0
Null source row   : 0
Null checksum     : 0
Null pipeline run : 0
Duplicate raw ID  : 0
============================================================
✅ BRONZE QUALITY GATE: PASS
Bronze layer siap digunakan oleh Silver.